# Generated by Django 3.2.20 on 2024-01-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'service',
                'managed': False,
            },
        ),
    ]
