# Generated by Django 3.2.20 on 2024-01-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('med_recd', models.CharField(max_length=65)),
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'medical_record',
                'managed': False,
            },
        ),
    ]
