# Generated by Django 3.2.20 on 2024-01-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
                ('address', models.CharField(max_length=55)),
                ('age', models.CharField(max_length=2)),
                ('gender', models.CharField(max_length=15)),
                ('phone_no', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'patient',
                'managed': False,
            },
        ),
    ]
