# Generated by Django 3.2.20 on 2024-01-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('age', models.CharField(max_length=2)),
                ('gender', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=55)),
                ('e_mail', models.CharField(db_column='e-mail', max_length=30)),
                ('phone_no', models.CharField(db_column='phone no', max_length=10)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
