# Generated by Django 3.2.20 on 2024-01-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doct_id', models.AutoField(primary_key=True, serialize=False)),
                ('doct_name', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=55)),
                ('phone_no', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=55)),
                ('experience', models.CharField(max_length=15)),
                ('qualification', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'doctor',
                'managed': False,
            },
        ),
    ]
