# Generated by Django 3.2.20 on 2024-01-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=49)),
                ('e_mail', models.CharField(db_column='e-mail', max_length=48)),
                ('phone_no', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'department',
                'managed': False,
            },
        ),
    ]
